import {useMemo,useRef} from 'react';
import {useFrame} from '@react-three/fiber';
import * as THREE from 'three';
import {flight} from '../flight';
import {pathX,ringAt} from '../world';
import {useGame} from '../store';
import {PaperModel} from './Airplane';
import {playSound} from './AudioManager';
function Ring({slot}:{slot:number}){const ref=useRef<THREE.Group>(null),index=useRef(-1),collected=useRef(false),lastRun=useRef(-1);useFrame(({clock})=>{if(!ref.current)return;const s=useGame.getState();const base=Math.max(0,Math.floor((flight.distance-18)/32));const i=base+((slot-base)%14+14)%14;if(index.current!==i||lastRun.current!==s.run){index.current=i;collected.current=false;lastRun.current=s.run;}const p=ringAt(i);ref.current.position.set(p.x,p.y,-p.d);ref.current.rotation.z=clock.elapsedTime*.15;ref.current.visible=!collected.current;const dz=p.d-flight.distance;if(!collected.current&&s.status==='playing'&&Math.abs(dz)<2&&Math.hypot(flight.position.x-p.x,flight.position.y-p.y)<2.65){collected.current=true;if(s.mode==='journey')s.ring();playSound('ring');ref.current.visible=false;}else if(!collected.current&&dz< -2&&dz> -5){collected.current=true;if(s.mode==='journey')useGame.setState({combo:0});}});return <group ref={ref}><mesh><torusGeometry args={[2.7,.075,8,64]}/><meshStandardMaterial color="#ffd67c" emissive="#ffbe52" emissiveIntensity={2.2} toneMapped={false}/></mesh><mesh><torusGeometry args={[2.92,.014,4,64]}/><meshBasicMaterial color="#ffe7a4" transparent opacity={.6}/></mesh>{[0,1,2,3].map(v=><mesh key={v} position={[Math.cos(v*Math.PI/2)*2.7,Math.sin(v*Math.PI/2)*2.7,0]} rotation={[0,0,Math.PI/4]}><octahedronGeometry args={[.16]}/><meshBasicMaterial color="#fff5cb"/></mesh>)}</group>}
function Crane({slot}:{slot:number}){const ref=useRef<THREE.Group>(null),id=useRef(-1),got=useRef(false),run=useRef(-1);useFrame(({clock})=>{if(!ref.current)return;const base=Math.max(0,Math.floor((flight.distance-10)/96));const i=base+((slot-base)%5+5)%5;if(id.current!==i||run.current!==useGame.getState().run){id.current=i;got.current=false;run.current=useGame.getState().run}const d=80+i*96;const x=pathX(d)+Math.sin(i)*4,y=12+Math.sin(clock.elapsedTime*2)*.35;ref.current.position.set(x,y,-d);ref.current.rotation.y=Math.sin(clock.elapsedTime)*.3;ref.current.visible=!got.current;if(!got.current&&useGame.getState().status==='playing'&&Math.abs(d-flight.distance)<2&&Math.hypot(flight.position.x-x,flight.position.y-y)<3){got.current=true;useGame.getState().crane();playSound('crane')}});return <group ref={ref}><PaperModel scale={.55} crane/><mesh rotation={[Math.PI/2,0,0]}><torusGeometry args={[1.6,.02,4,32]}/><meshBasicMaterial color="#f9edcb"/></mesh></group>}
function WindCurrent({slot}:{slot:number}){const ref=useRef<THREE.Group>(null);useFrame(({clock},dt)=>{if(!ref.current)return;const base=Math.max(0,Math.floor(flight.distance/180));const i=base+((slot-base)%4+4)%4;const d=120+i*180;const x=pathX(d)+8;ref.current.position.set(x,0,-d);ref.current.children.forEach((o,j)=>{o.position.y=(clock.elapsedTime*3+j*2)%18;o.rotation.y=clock.elapsedTime+j;o.scale.setScalar(.75+o.position.y/35)});if(useGame.getState().status==='playing'&&Math.abs(flight.distance-d)<7&&Math.abs(flight.position.x-x)<5&&flight.position.y<22){flight.position.y+=dt*4;useGame.setState({notice:'Riding a rising wind'})}});return <group ref={ref}>{Array.from({length:6},(_,i)=><mesh key={i} rotation={[Math.PI/2,0,0]}><torusGeometry args={[3,.025,4,48,Math.PI*1.2]}/><meshBasicMaterial color="#f6f1d1" transparent opacity={.28}/></mesh>)}</group>}
function Checkpoints(){const last=useRef(-1),lastRun=useRef(-1);useFrame(()=>{const s=useGame.getState();if(lastRun.current!==s.run){last.current=-1;lastRun.current=s.run}if(s.status!=='playing')return;const i=Math.floor(flight.distance/300);const d=i*300+65;if(i===last.current||Math.abs(flight.distance-d)>1.5)return;last.current=i;const dx=Math.abs(flight.position.x-pathX(d));if(s.mode==='journey'&&((dx>6.3&&dx<8.5&&flight.position.y<16)||(dx<10&&flight.position.y>12.6&&flight.position.y<16.5))){s.crash();playSound('crash');return;}if(dx<6.3&&flight.position.y>1&&flight.position.y<12.6){useGame.setState({notice:'Torii checkpoint · A new breath',energy:Math.min(100,s.energy+15),score:s.score+(s.mode==='journey'?250:0)});playSound('gate')}});return null;}
export default function Collectibles(){const rings=useMemo(()=>Array.from({length:14},(_,i)=>i),[]);return <>{rings.map(i=><Ring key={i} slot={i}/>)}{[0,1,2,3,4].map(i=><Crane key={i} slot={i}/>)}{[0,1,2,3].map(i=><WindCurrent key={i} slot={i}/>)}<Checkpoints/></>}
