import {useRef,useMemo,useLayoutEffect} from 'react';
import {useFrame} from '@react-three/fiber';
import * as THREE from 'three';
import {flight} from '../flight';
import {random} from '../world';
import {useGame} from '../store';
const obj=new THREE.Object3D();
function Petals(){const mesh=useRef<THREE.InstancedMesh>(null);const particles=useMemo(()=>{const r=random(438);return Array.from({length:130},()=>({x:(r()-.5)*90,y:r()*30,z:(r()-.5)*100,s:.06+r()*.09,a:r()*6}))},[]);useFrame(({clock})=>{if(!mesh.current)return;const t=clock.elapsedTime;particles.forEach((p,i)=>{obj.position.set(flight.position.x+((p.x+t*1.8+45)%90)-45,((p.y-t*.5)%30+30)%30,flight.position.z+p.z+Math.sin(t+p.a)*3);obj.rotation.set(t*.7+p.a,t*.4,t*.8+p.a);obj.scale.set(p.s,p.s*.5,p.s);obj.updateMatrix();mesh.current!.setMatrixAt(i,obj.matrix)});mesh.current.instanceMatrix.needsUpdate=true;});return <instancedMesh ref={mesh} args={[undefined,undefined,130]} frustumCulled={false}><circleGeometry args={[1,5]}/><meshStandardMaterial color="#f5c4cf" side={THREE.DoubleSide} roughness={1}/></instancedMesh>}
function Mountains(){const group=useRef<THREE.Group>(null);useFrame(()=>{if(group.current)group.current.position.z=flight.position.z});return <group ref={group}>
 <group position={[55,0,-330]}><mesh position={[0,40,0]}><coneGeometry args={[100,95,12]}/><meshStandardMaterial color="#969da6" flatShading/></mesh><mesh position={[0,74,0]}><coneGeometry args={[29,27,12]}/><meshStandardMaterial color="#f5e9df" flatShading/></mesh></group>
 {[-1,1].flatMap(s=>Array.from({length:5},(_,i)=><mesh key={`${s}${i}`} position={[s*(95+i*43),5,-190-i*35]} scale={[65,50+i*8,60]}><icosahedronGeometry args={[1,1]}/><meshStandardMaterial color={i%2?'#a5aaa1':'#b1b0a4'} flatShading/></mesh>))}
 <mesh position={[-115,104,-370]}><sphereGeometry args={[20,32,24]}/><meshBasicMaterial color="#ffe3b0" fog={false}/></mesh>
 </group>}
function Clouds(){const group=useRef<THREE.Group>(null),mesh=useRef<THREE.InstancedMesh>(null);useLayoutEffect(()=>{if(!mesh.current)return;const r=random(127);for(let i=0;i<65;i++){const cluster=Math.floor(i/5);obj.position.set((cluster%5-2)*70+(r()-.5)*30,62+Math.floor(cluster/5)*18+r()*5,-80-Math.floor(cluster/5)*100-r()*35);obj.scale.set(10+r()*12,3+r()*3,8+r()*10);obj.rotation.set(0,r(),0);obj.updateMatrix();mesh.current.setMatrixAt(i,obj.matrix);mesh.current.setColorAt(i,new THREE.Color(i%3?'#f3d8c9':'#ecc7bc'));}mesh.current.instanceMatrix.needsUpdate=true},[]);useFrame(({clock})=>{if(group.current){group.current.position.z=flight.position.z;group.current.position.x=Math.sin(clock.elapsedTime*.015)*9;}});return <group ref={group}><instancedMesh ref={mesh} args={[undefined,undefined,65]}><icosahedronGeometry args={[1,2]}/><meshStandardMaterial roughness={1} emissive="#e9c1b5" emissiveIntensity={.22}/></instancedMesh></group>}
export default function Environment(){const light=useRef<THREE.DirectionalLight>(null);const target=useMemo(()=>new THREE.Object3D(),[]);const quality=useGame(s=>s.quality);useFrame(()=>{if(light.current){light.current.position.set(flight.position.x-40,60,flight.position.z+25);target.position.set(flight.position.x,0,flight.position.z-30);target.updateMatrixWorld()}});return <><color attach="background" args={['#e9d3c6']}/><fog attach="fog" args={['#e6d4c8',85,420]}/><hemisphereLight args={['#fff0df','#8c9c83',2]}/><ambientLight intensity={.35}/><primitive object={target}/><directionalLight ref={light} target={target} color="#ffe0b0" intensity={3} castShadow={quality} shadow-mapSize={[2048,2048]} shadow-camera-left={-70} shadow-camera-right={70} shadow-camera-top={70} shadow-camera-bottom={-70} shadow-camera-far={180} shadow-bias={-.001} shadow-normalBias={.12}/><Mountains/><Clouds/><Petals/></>}
