import {useEffect,useRef} from 'react';
import {useFrame} from '@react-three/fiber';
import {MathUtils} from 'three';
import {flight,input} from '../flight';
import {useGame} from '../store';
import {chunkData,hitObstacle,pathX,ringAt} from '../world';
import {playSound} from './AudioManager';
export default function FlightController(){const run=useGame(s=>s.run);const tick=useRef(0),flutter=useRef(0);const cache=useRef({i:-999,items:chunkData(0)});
 useEffect(()=>{const s=useGame.getState();flight.distance=s.startRegion*650;flight.position.set(pathX(flight.distance),11,-flight.distance);flight.velocity.set(0,0,0);flight.steerX=0;flight.steerY=0;flight.speed=18;input.keys.clear();input.pointer=false;input.x=0;input.y=0;input.boost=false;input.brake=false;},[run]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)&&useGame.getState().status==='playing')e.preventDefault();input.keys.add(e.code);if(e.repeat)return;if(e.code==='Escape'||e.code==='KeyP')useGame.getState().pause();if(e.code==='KeyG')useGame.getState().toggle('auto')};const up=(e:KeyboardEvent)=>input.keys.delete(e.code);const blur=()=>{input.keys.clear();input.pointer=false;input.boost=false;input.brake=false;if(useGame.getState().status==='playing')useGame.getState().pause()};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',blur)}},[]);
 useFrame((_,delta)=>{const s=useGame.getState();if(s.status!=='playing')return;const dt=Math.min(delta,.04);flight.time+=dt;const keys=input.keys;let x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0);let y=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0);if(!x&&input.pointer)x=input.x;if(!y&&input.pointer)y=input.y;if(s.auto&&!x&&!y){const next=ringAt(Math.max(0,Math.ceil((flight.distance-35)/32)));x=MathUtils.clamp((next.x-flight.position.x)*.5,-1,1);const gate= Math.floor(flight.distance/300)*300+65; const targetY=gate-flight.distance>-8&&gate-flight.distance<35?Math.min(next.y,11.4):next.y;y=MathUtils.clamp((targetY-flight.position.y)*.6+.075,-1,1)}
 flight.steerX=MathUtils.damp(flight.steerX,x,4.2,dt);flight.steerY=MathUtils.damp(flight.steerY,y,4.2,dt);flight.boost=(keys.has('Space')||input.boost)&&s.energy>0;flight.brake=keys.has('ShiftLeft')||keys.has('ShiftRight')||input.brake;const targetSpeed=(18+Math.min(12,flight.distance/700))*(flight.boost?1.8:flight.brake?.48:1)-flight.steerY*2;flight.speed=MathUtils.damp(flight.speed,targetSpeed,2,dt);flight.distance+=flight.speed*dt;
 const wind=Math.sin(flight.time*.6)*.28;flight.velocity.x=MathUtils.damp(flight.velocity.x,flight.steerX*12+wind,3,dt);flight.velocity.y=MathUtils.damp(flight.velocity.y,flight.steerY*9-.32+(flight.boost?1.1:0),2.5,dt);flight.position.x=MathUtils.clamp(flight.position.x+flight.velocity.x*dt,-92,92);flight.position.y=Math.min(45,flight.position.y+flight.velocity.y*dt);flight.position.z=-flight.distance;
 const currentIndex=Math.floor(flight.distance/100);if(cache.current.i!==currentIndex)cache.current={i:currentIndex,items:[...chunkData(currentIndex-1),...chunkData(currentIndex),...chunkData(currentIndex+1)]};
 if(s.mode==='journey'&&(flight.position.y<.7||cache.current.items.some(o=>hitObstacle(flight.position.x,flight.position.y,flight.distance,o)))){playSound('crash');s.crash()}
 if(s.mode==='free'&&flight.position.y<2){flight.position.y=2;flight.velocity.y=1;}
 if(Math.abs(flight.steerX)+Math.abs(flight.steerY)>.6&&flight.time-flutter.current>.25){playSound('flutter');flutter.current=flight.time;}
 tick.current+=dt;if(tick.current>.08){tick.current=0;useGame.setState({distance:flight.distance,energy:MathUtils.clamp(s.energy+(flight.boost?-23:1.2)*.08,0,100),region:Math.floor(flight.distance/650)%5});}
 });return null;}
