import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,Volume2,VolumeX,Pause,Play,RotateCcw,Settings2,X,Wind,MoveUpRight,Leaf,ChevronRight,Check,Navigation,Maximize,Minimize} from 'lucide-react';
import {useGame,regions} from '../store';
import {input} from '../flight';
import {startAudio} from './AudioManager';
function PlaneIcon({size=28}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 48 48" fill="none" aria-hidden="true"><path d="m4 20 39-13-14 35-8-15-17-7Z" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round"/><path d="M21 27 43 7 26 31" stroke="currentColor" strokeWidth="1.3"/></svg>}
export default function HUD(){const s=useGame(),[selected,setSelected]=useState(0),[notice,setNotice]=useState(''),[fullscreen,setFullscreen]=useState(false);const menu=s.status==='menu',playing=s.status==='playing';
 useEffect(()=>{setNotice(s.notice);const t=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(t)},[s.notice]);
 useEffect(()=>{const update=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',update);return()=>document.removeEventListener('fullscreenchange',update)},[]);
 const begin=(mode:'journey'|'free',region=0)=>{void startAudio();s.start(mode,region)};
 const goFull=()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen?.().catch(()=>{});};
 return <div className={`interface ${menu?'is-menu':''}`}>
 <header className="topbar"><button className="brand" onClick={()=>{if(playing)s.pause();else if(s.status==='paused'||s.status==='crashed')s.home()}} aria-label="Paper Sky home"><PlaneIcon/><span>PAPER SKY<small>A JOURNEY THROUGH JAPAN</small></span></button><div className="top-actions">{menu&&<button className="text-button journey-link" onClick={()=>s.toggle('guide')}>THE ART OF FLIGHT <ArrowUpRight size={14}/></button>}<button className="icon-button" aria-label={s.sound?'Mute sound':'Enable sound'} onClick={()=>{s.toggle('sound');void startAudio()}}>{s.sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><button className="icon-button" aria-label="Settings" onClick={()=>{if(playing)s.pause();s.toggle('settings')}}><Settings2 size={18}/></button>{!menu&&<button className="icon-button solid" aria-label={playing?'Pause flight':'Resume flight'} onClick={s.pause}>{playing?<Pause size={17}/>:<Play size={17}/>}</button>}</div></header>
 {menu&&<><main className="intro"><div className="eyebrow"><span/> A LITTLE PAPER. AN ENDLESS SKY.</div><h1>PAPER<br/><span>SKY</span><i>紙の空</i></h1><p className="subtitle">A Journey Through Japan</p><p className="intro-copy">Fold your worries away.<br/>Follow the wind somewhere beautiful.</p><div className="start-actions"><button className="primary" onClick={()=>begin('journey')}>Start Flight <ArrowRight size={19}/></button><button className="secondary" onClick={()=>begin('free',selected)}>Free Explore <ArrowUpRight size={17}/></button></div><div className="small-note"><Leaf size={13}/> No rush. Just you and the horizon.</div></main>
 <aside className="vertical-poem"><span>風にまかせて</span><small>LET THE WIND TAKE YOU</small></aside>
 <div className="scene-caption"><span className="caption-line"/><span>35° 21′ N &nbsp; 138° 43′ E<small>Somewhere between a dream and Japan.</small></span></div>
 <footer className="journey-footer"><div className="journey-title"><span className="eyebrow">FIVE PLACES. ONE OPEN SKY.</span><span>Your journey unfolds <ArrowRight size={15}/></span></div><div className="region-list">{regions.map((r,i)=><button className={`region-option ${selected===i?'selected':''}`} key={r.name} onClick={()=>setSelected(i)} aria-pressed={selected===i}><span className="region-index">0{i+1}</span><span>{r.name}<small>{r.jp}</small></span>{selected===i&&<span className="region-dot"/>}</button>)}</div><div className="footer-bottom"><span><span className="status-dot"/> AN INTERACTIVE MOMENT OF CALM</span><span className="headphone-hint">Best experienced with headphones <Volume2 size={12}/></span></div></footer></>}
 {!menu&&<><div className="flight-region"><span className="eyebrow">CHAPTER 0{s.region+1} <span className="tiny-line"/></span><h2>{regions[s.region].name}</h2><p>{regions[s.region].jp} <span>•</span> {s.mode==='free'?'Wander without limits':'Follow the wind'}</p></div><div className="flight-stats"><div><small>DISTANCE</small><strong>{Math.max(0,Math.floor(s.distance-s.startRegion*650)).toLocaleString()}<em>m</em></strong></div>{s.mode==='journey'&&<><div><small>SCORE</small><strong>{s.score.toLocaleString().padStart(4,'0')}</strong></div><div className="combo"><small>FLOW</small><strong>×{Math.max(1,Math.min(5,Math.ceil(s.combo/3)))}</strong></div></>}</div>
 <div className={`notification ${notice&&playing?'visible':''}`}><span>✧</span>{notice}</div>
 <div className="flight-bottom"><div className="energy"><div><Wind size={17}/><span>WIND ENERGY</span><small>{Math.round(s.energy)}%</small></div><div className="energy-track"><span style={{width:`${s.energy}%`}}/></div><small>HOLD <kbd>SPACE</kbd> TO CATCH THE WIND</small></div><div className="control-hints"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> or move mouse</span><span><kbd>SHIFT</kbd> air brake</span></div><button className={`auto-button ${s.auto?'enabled':''}`} onClick={()=>s.toggle('auto')}><Wind size={16}/><span>Auto-glide <small>{s.auto?'ON':'OFF'}</small></span></button></div>
 <div className="mobile-controls"><button onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);input.brake=true}} onPointerUp={()=>input.brake=false} onPointerCancel={()=>input.brake=false}>BRAKE</button><span>DRAG TO STEER</span><button onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);input.boost=true}} onPointerUp={()=>input.boost=false} onPointerCancel={()=>input.boost=false}><Wind size={20}/> BOOST</button></div></>}
 <button className="fullscreen" aria-label={fullscreen?'Exit fullscreen':'Enter fullscreen'} onClick={goFull}>{fullscreen?<Minimize size={15}/>:<Maximize size={15}/>}</button>
 {(s.status==='paused'||s.status==='crashed')&&!s.settings&&!s.guide&&<div className="modal-backdrop"><section className="modal pause-modal"><div className="modal-symbol"><PlaneIcon size={42}/></div><span className="eyebrow">{s.status==='crashed'?'EVERY LANDING IS A NEW BEGINNING':'A MOMENT OF STILLNESS'}</span><h2>{s.status==='crashed'?'A gentle landing.':'Let the world wait.'}</h2><p>{s.status==='crashed'?'The sky will be here when you’re ready.':'Take a breath. Your journey is right here.'}</p>{s.status==='crashed'&&<div className="results"><div><small>DISTANCE</small><strong>{Math.floor(s.distance-s.startRegion*650)}m</strong></div><div><small>SCORE</small><strong>{s.score}</strong></div><div><small>PERSONAL BEST</small><strong>{s.best}</strong></div></div>}<button className="primary" onClick={()=>s.status==='paused'?(void startAudio(),s.pause()):begin(s.mode,s.startRegion)}>{s.status==='paused'?'Continue the Journey':'Fly Again'}{s.status==='paused'?<Play size={16}/>:<RotateCcw size={16}/>}</button>{s.status==='paused'&&<button className="secondary" onClick={()=>begin(s.mode,s.startRegion)}>Start a new flight <RotateCcw size={14}/></button>}<button className="text-button" onClick={s.home}>BACK TO THE HILLSIDE <ArrowUpRight size={14}/></button></section></div>}
 {s.settings&&<div className="modal-backdrop"><section className="modal"><button className="close" aria-label="Close settings" onClick={()=>s.toggle('settings')}><X size={20}/></button><span className="eyebrow">MAKE YOURSELF AT HOME</span><h2>Your kind of calm.</h2><p>A few little things to make the flight yours.</p>{([{key:'sound',title:'Sounds of Japan',desc:'Procedural music, soft wind & birdsong.'},{key:'auto',title:'Auto-glide',desc:'Let the breeze guide you through the rings.'},{key:'quality',title:'Cinematic effects',desc:'Soft shadows & a gentle golden bloom.'}] as const).map(o=><button className="setting-row" key={o.key} onClick={()=>{s.toggle(o.key);if(o.key==='sound')void startAudio()}} role="switch" aria-checked={s[o.key]}><span>{o.title}<small>{o.desc}</small></span><span className={`toggle ${s[o.key]?'on':''}`}><i/></span></button>)}<button className="secondary" onClick={()=>{s.toggle('settings');s.toggle('guide')}}>Flight controls <ArrowRight size={16}/></button></section></div>}
 {s.guide&&<div className="modal-backdrop"><section className="modal guide"><button className="close" aria-label="Close flight guide" onClick={()=>s.toggle('guide')}><X size={20}/></button><span className="eyebrow">THE ART OF FLIGHT</span><h2>A little less gravity.</h2><p>Small movements. Beautiful possibilities.</p><div className="guide-row"><Navigation/><span>Find your flow<small>Move your mouse, drag on mobile, or use WASD / arrow keys. Up climbs, down dives.</small></span></div><div className="guide-row"><Wind/><span>Borrow a little wind<small>Space boosts. Shift slows you down. Collect white origami cranes to refill your wind energy.</small></span></div><div className="guide-row"><span className="gold-ring"/><span>Follow the golden moments<small>Fly through rings to build your combo. Torii gates reward a checkpoint. Pale spirals lift you up.</small></span></div><div className="guide-row"><Leaf/><span>Go at your own pace<small>G toggles auto-glide. Escape pauses. Free Explore has no scores or collisions.</small></span></div><button className="primary" onClick={()=>s.toggle('guide')}>I’m ready for the sky <ArrowRight size={17}/></button></section></div>}
 </div>
}
